apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app.kubernetes.io/name: mongod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-remote
  labels:
    app.kubernetes.io/name: mongod
    app: mongod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongod
      app: mongod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongod
        app: mongod
    spec:
      hostNetwork: true
      containers:
        - name: mongocontainer
          image: mongo:4.0.21
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
            name: mongocontainer
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mongod
  name: mongo-remote
spec:
  ports:
  - name: https
    port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongod
