kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-config
data:
  MONGO_IP: "10.43.255.98"
  MONGO_PORT: "27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler
  labels:
    app: ruler
spec:
  selector:
    matchLabels:
      app: ruler
  template:
    metadata:
      labels:
        app: ruler
    spec:
      hostNetwork: true
      containers:
      - name: ruler
        image: gkorod/ruler:v1.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: platform-config

      nodeSelector:
        beta.kubernetes.io/os: linux
