apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  namespace: rabbit
spec:
  containers:
  - name: operator-container
    image: gkorod/operator:v0.1
    imagePullPolicy: Always
    env:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    envFrom:
      - configMapRef:
          name: appconfig
  - name: publish-container
    image: gkorod/publish:v0.1
    imagePullPolicy: Always
    env:
      - name: RABBITMQ_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mu-rabbit-rabbitmq
            key: rabbitmq-password
    ports:
      - containerPort: 4321
        name: publishport
    envFrom:
      - configMapRef:
          name: publishconfig


