apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: nodered/node-red
        ports:
        - containerPort: 1880
        stdin: true
        tty: true
        resources: {}
        volumeMounts:
        - name: nodered-storage
          mountPath: /data  # Mount path inside the container
      volumes:
      - name: nodered-storage
        persistentVolumeClaim:
          claimName: nodered-pvc

